# Goal definition
bool dock  # Request to start docking

---
# Result definition
bool success  # Indicates if docking was successful

---
# Feedback definition
float64 remaining_distance  # Remaining distance to dock in meters
